config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'static#home'

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#login"
  get '/logout', to: "sessions#destroy", as: "logout"
  get '/auth/google_oauth2/callback' => 'sessions#new_from_google'
  post '/create_from_google',to: "sessions#create"
  post '/new_comment', to: "comments#new"
  
  resources :events, :users, :comments, :categories
  
  resources :users, only:[:show] do 
    resources :events, only: [:index, :new]
  end
  
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :organized_events, foreign_key: "organization_id", class_name: "Event"
    has_many :commented_comments, foreign_key: "organization_id", class_name: "Comment"
    has_many :being_commented_comments, foreign_key: "volunteer_id", class_name: "Comment"
    has_many :joined_events, through: :being_commented_comments, :source => :event

    validates :name, :email, presence: true

    validates :email, uniqueness: true
    validates :email, confirmation: true
    
    scope :is_organization, -> { where(is_organization: true) }
    scope :is_not_organization, -> { where(is_organization: false) }

   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:show]
    
    
    def new
        @user = User.new
    end

    def index
      @users_organization = User.all.is_organization
      @users_volunteer = User.all.is_not_organization
    end

    def create
        @user = User.new(user_params)
        if @user.save
          session[:user_id]=@user.id
          redirect_to user_path(@user)
        else
          render 'new'
        end
    end

    def show
      @current_user = current_user
      @user = User.find_by id: params[:id]
      if @user
          related_events_and_comments
          render 'show' 
      else
        flash[:error] = "That user doesn't exist."
        redirect_to '/'
      end
    end



    private
      def user_params
        params.require(:user).permit(:name,:password,:email,:email_confirmation,:bio,:is_organization)
      end

      def related_events_and_comments
        if @user.is_organization
          @events = @user.organized_events
          @comments = @user.commented_comments
        else
          @events = @user.joined_events
          @comments = @user.being_commented_comments
        end
      end



end

app/helpers/users_helper.rb
module UsersHelper

    def is_organization_field?(user,comments)
        if user.is_organization 
          "As an organization, #{user.name} makes #{comments.size} comment(s)" 
        else
          "As an volunteer, #{user.name} receives #{comments.size} comment(s)" 
        end 
    end

end

app/views/users/_user.html.erb
<%= f.label :name %>
<%= f.text_field :name, :value=>user.name%><br>
<%= f.label :email %>
<%= f.text_field :email, :value=>user.email%><br>
<%= f.label :password %>
<%= f.password_field :password %><br>
<%= f.label :bio %><br>
<%= f.text_area :bio %><br>

<%= f.label :is_organization %>
<%= f.check_box :is_organization %><br>
<%= f.submit %>

app/views/users/index.html.erb
<h1>Check out our organizations and volunteers now </h1>


<h2>Organizations: </h2>

<ul>
    <% @users_organization.each do |o|%>
        <li><%= link_to o.name, user_path(o) %></li>
    <% end %>
</ul>

<h2>Volunteers: </h2>

<ul>
    <% @users_volunteer.each do |o|%>
        <li><%= link_to o.name, user_path(o) %></li>
    <% end %>
</ul>



app/views/users/new.html.erb
<h1>Sign up</h1>


<%= form_for @user do |f|%>
  <%= render partial: "layouts/error", locals: {object: @user} %>
 
  <%= render partial: "users/user", locals: {f: f, user: @user} %>

<% end %>

app/views/users/show.html.erb
<h1><%= "Hello #{@user.name}!" %></h1>

<h2><%= is_organization_field?(@user,@comments)%></h2>

<% unless @comments.empty? %>
  <ul>
    <% @comments.each do |c|%>
      <li><%= link_to c.content, comment_path(c)%>
      <%= link_to "Edit", edit_comment_path(c)%> 
      <%= link_to "Delete", c, method: :delete, data: { confirm: "Really?" } %>
      </li>
    <% end %>
  </ul>   
<% end %>

<% unless @events.empty? %>
<h2><%= @user.name%> has <%= @events.size %> <%= link_to "events",user_events_path(@user) %> </h2>  
<% end %>

<% if @current_user.is_organization && @current_user != @user %>
  <%= form_tag("/new_comment") do %>
    <%= hidden_field_tag :volunteer_id, value = @user.id %>
    <%= submit_tag "Comment on this volunteer" %>
  <% end %>
<% end %>

<% if @current_user.is_organization %>
  <%= link_to "create your own event!", new_user_event_path(@current_user) %>
<% end %>







