config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'static#home'

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#login"
  get '/logout', to: "sessions#destroy", as: "logout"
  get '/auth/google_oauth2/callback' => 'sessions#new_from_google'
  post '/create_from_google',to: "sessions#create"
  post '/new_comment', to: "comments#new"
  
  resources :events, :users, :comments, :categories
  
  resources :users, only:[:show] do 
    resources :events, only: [:index, :new]
  end
  
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :organization, class_name: "User"
    has_many :comments
    has_many :locations
    has_many :volunteers, through: :comments
    accepts_nested_attributes_for :locations
    belongs_to :category


    validates :organization_id, :contact_email, :name, presence: true
    scope :is_free, ->{where(is_free: true)}
    scope :is_finish, ->{ where("end_date < ?", Time.zone.now) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user, only: [:show, :edit, :new, :destroy]
    before_action :find_event, only: [:show, :edit, :update, :destroy]
    

    def index
        if params[:user_id]
            @user = User.find_by :id=>params[:user_id]
            if @user && @user.is_organization
              @events = @user.organized_events
            elsif @user && !@user.is_organization
              @events = @user.joined_events
            else
              flash[:error] = "The user doesn't exist."
              redirect_to users_path
            end
        else
            @events = Event.all
        end   
    end

    def new
        @user = current_user
        if @user.is_organization
           @event = Event.new
           @location1 = @event.locations.build
        else
           flash[:error] = "Only organization user can create an event."
           redirect_to events_path
        end
    end

    def create
        @event = Event.new(event_params)
        @user = current_user
        @event.organization = @user
        if @event.save
            redirect_to event_path(@event)
        else
            render 'new'
        end
    end

    def edit
        @user = @event.organization
        authorized_user?
    end

    def show
        @organization = @event.organization
        @volunteers = @event.volunteers
        @comments = @event.comments   
    end

    def update
        @event.update(event_params)
        redirect_to event_path(@event)
    end
    
    def destroy
        if current_user == @event.organization
            @event.delete
            redirect_to events_path
        else
            flash[:error] = "Only the creator can delete this event."
            redirect_to event_path(@event)
        end
    end


private
    def find_event
        @event = Event.find_by :id=>params[:id] 
        unless @event
          flash[:error] = "There is no such event."
          redirect_to '/events'
        end
      end

      def event_params
        params.require(:event).permit(:name,:contact_email,:phone_number, :is_free,:description, :start_date, :end_date, :category_id,
        locations_attributes: [
            :street_address_1,
            :street_address_2,
            :city,
            :state,
            :zipcode
          ])
      end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |f|%>
  <%= render partial: "layouts/error", locals: {object: @event} %>


    <%= f.label :name, :value=>"Event name" %>
    <%= f.text_field :name%><br>

    <%= f.label :contact_email %>
    <%= f.text_field :contact_email, :value=>@user.email %><br>

    <%= f.label :phone_number %>
    <%= f.text_field :phone_number %><br>

    <%= f.label :description %>
    <%= f.text_area :description %><br>

    <%= f.label :is_free, "Free?" %>
    <%= f.check_box :is_free %><br>

    <%= f.label :start_date %>
    <%= f.date_select :start_date %><br>

    <%= f.label :end_date %>
    <%= f.date_select :end_date %><br>

    <%= f.collection_select :category_id, Category.all, :id, :name %><br>




    <%= f.label "Event address" %><br>
    <%= f.fields_for :locations do |l| %>
        <%= l.label :street_address_1 %>
        <%= l.text_field :street_address_1 %><br>
     
        <%= l.label :street_address_2 %>
        <%= l.text_field :street_address_2 %><br>
     
        <%= l.label :city %>
        <%= l.text_field :city %><br>
     
        <%= l.label :state %>
        <%= l.text_field :state %><br>
     
        <%= l.label :zipcode %>
        <%= l.text_field :zipcode %><br>

    <% end %>


    <%= f.submit%>
<% end %>


app/views/events/index.html.erb
<h1>
  <% if @user %>
    <%= @user.name %>'s Events:
  <% else %>
    <%= "Events" %>
  <% end %>
</h1>


<ul>
<% @events.each do |e| %>
    <% org = e.organization %>
    <li><%= link_to e.name, event_path(e)%> is held by <%= link_to org.name, user_path(org) %></li>
<% end %>
</ul>

<h3><%= link_to "Create Your Own Event!", new_event_path %></h3>




app/views/events/show.html.erb
<h1><%= @event.name %></h1>


<h2>Basic Information: </h2>
Organization: <%= link_to @organization.name, user_path(@organization)%><br>

<% if @event.category %>
  Category: <%= link_to @event.category.name, category_path(@event.category)%><br>
<% end %>

<% if @event.start_date %>
  Start date: <%= @event.start_date.strftime("%B %d, %Y") %><br>
<% end %>

<% if @event.end_date %>
  End date: <%= @event.end_date.strftime("%B %d, %Y") %><br>
<% end %>

<% if @event.description %>
  Description: <%= @event.description %><br>
<% end %>

<%= @event.is_free ? "Free Event":"Not Free Event"%><br>



<h2>Contact:</h2>
Contact email: <%= @event.contact_email %><br>
<% if @event.phone_number %> 
  Phone: <%= @event.phone_number %><br>
<% end %>



<% unless @volunteers.empty? %>
  <h2>Volunteers who signed for this event:</h2>
  <ul>
    <% @volunteers.each do |v|%>
      <li><%= link_to v.name, user_path(v)%></li>
    <% end %>
  </ul>   
<% end %>

<% unless @comments.empty? %>
  <h2>Comments about this event:</h2>
  <ul>
    <% @comments.each do |c|%>
      <li><%= link_to c.content, comment_path(c)%></li>
    <% end %>
  </ul><br>   
<% end %>
  

  <br>
  <%= link_to "Edit the event", edit_event_path(@event) %><br>
  <%= link_to "Delete the event", @event, method: :delete, data: { confirm: "Really?" } %>


