config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'static#home'

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#login"
  get '/logout', to: "sessions#destroy", as: "logout"
  get '/auth/google_oauth2/callback' => 'sessions#new_from_google'
  post '/create_from_google',to: "sessions#create"
  post '/new_comment', to: "comments#new"
  
  resources :events, :users, :comments, :categories
  
  resources :users, only:[:show] do 
    resources :events, only: [:index, :new]
  end
  
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :events
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

   def index
    @categories = Category.all
   end
   
   def create
   end

   def show
     @category = Category.find_by id: params[:id]
     @events = @category.events
     if @category
        render 'show'
     else
        flash[:error] = "That category doesn't exist."
        redirect_to '/categories'
     end
   end

end

app/views/categories/index.html.erb
<ul>
<% @categories.each do |c| %>
    <li><%= link_to c.name, category_path(c)%></li>
<% end %>
</ul>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<% if @events.any? %>
<%= "Events under it:" %>
<% end %>

<ul>
<% @events.each do |e| %>
    <li><%= link_to e.name, event_path(e)%></li>
<% end %>
</ul>